version: "3"
services:
  # application:
  #   build: .
  #   ports:
  #     - 5000:5000
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - 443:443
      - 8000:80
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
  openldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_DOMAIN=dexter.com.br
      - LDAP_ADMIN_PASSWORD=4linux
